name = "VVGA"
uuid = "96f120c5-03fe-48e8-bd80-3122d3912500"
authors = ["Mamta Dalal, Steven Sandoval"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
